name: CI Build and SonarQube Analysis

on:
  push:
    branches: [ "Testes" ]
  pull_request:
    branches: [ "Testes" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sonarqube:
        image: sonarqube:9.9-community
        ports:
          - 9000:9000
        options: >-
          --shm-size=4g
          --health-cmd="curl -f http://localhost:9000/api/system/health || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=12

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Wait for SonarQube to be ready
        run: |
          echo "Waiting for SonarQube..."
          until curl -s http://localhost:9000/api/system/health | grep -q '"status":"UP"'; do
            echo "Waiting for SonarQube to be ready..."
            sleep 5
          done

      - name: Build with Maven (using H2 for tests)
        env:
          SPRING_PROFILES_ACTIVE: test
        run: mvn clean install

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        run: mvn sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.token=$SONAR_TOKEN
