name: CI Build and SonarQube Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Faz o checkout do código
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Configura o Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3. Compila o projeto e roda os testes
      - name: Build with Maven
        run: mvn clean install

      # 4. Executa a análise do SonarQube
      - name: Run SonarQube Analysis
        env:
          # Configure o token do SonarQube como secret no GitHub (Settings > Secrets > Actions)
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        run: |
          mvn sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.token=$SONAR_TOKEN
